# Generated by Django 5.0.7 on 2024-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_venta_idalma'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='presioc',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
