# Generated by Django 5.0.7 on 2024-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_venta_presioc'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='dia',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='mes',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
