# Generated by Django 5.0.7 on 2024-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_venta_dia_remove_venta_mes_remove_venta_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
