# Generated by Django 5.0.7 on 2024-09-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
