# Generated by Django 5.0.7 on 2025-02-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='promot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('idNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.promot')),
            ],
        ),
    ]
