# Generated by Django 5.0.7 on 2025-02-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_promot_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promot',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
