# Generated by Django 5.0.7 on 2025-02-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_nombre_promot_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='idalmac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
