# Generated by Django 5.0.7 on 2024-09-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_pedido_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
    ]
