# Generated by Django 3.2.12 on 2024-07-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='almacenb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('presioc', models.FloatField()),
                ('presiob', models.FloatField()),
                ('ganancia', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
