# Generated by Django 3.2.12 on 2024-07-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenb',
            name='numinver',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
