# Generated by Django 3.2.12 on 2024-07-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_almacenb_numinver'),
    ]

    operations = [
        migrations.CreateModel(
            name='inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mes', models.CharField(max_length=2)),
                ('monto', models.FloatField()),
            ],
        ),
    ]
