# Generated by Django 3.2.12 on 2024-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_inversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversion',
            old_name='monto',
            new_name='montoganancia',
        ),
        migrations.AddField(
            model_name='inversion',
            name='montoinver',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
