# Generated by Django 5.0.7 on 2024-08-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_inversion_libre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenb',
            name='numinver',
        ),
    ]
