# Generated by Django 5.0.7 on 2024-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_remove_almacenb_numinver'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenb',
            name='existencia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
